[
  {
    "number": 918,
    "title": "Error: No module named 'httpx'",
    "created_at": "2025-02-07T15:50:35Z",
    "closed_at": "2025-02-07T16:51:33Z",
    "labels": [
      "bug"
    ],
    "url": "https://github.com/DS4SD/docling/issues/918",
    "body": "### Bug\nAfter install the latest version of Docling (v2.19.0), docling throws this error\n\n```\ndocling test-docling.pdf --to json --to md\nTraceback (most recent call last):\n  File \"/Users/jean/.pyenv/versions/3.12.1/bin/docling\", line 5, in <module>\n    from docling.cli.main import app\n  File \"/Users/jean/.pyenv/versions/3.12.1/lib/python3.12/site-packages/docling/cli/main.py\", line 43, in <module>\n    from docling.document_converter import DocumentConverter, FormatOption, PdfFormatOption\n  File \"/Users/jean/.pyenv/versions/3.12.1/lib/python3.12/site-packages/docling/document_converter.py\", line 44, in <module>\n    from docling.pipeline.standard_pdf_pipeline import StandardPdfPipeline\n  File \"/Users/jean/.pyenv/versions/3.12.1/lib/python3.12/site-packages/docling/pipeline/standard_pdf_pipeline.py\", line 29, in <module>\n    from docling.models.easyocr_model import EasyOcrModel\n  File \"/Users/jean/.pyenv/versions/3.12.1/lib/python3.12/site-packages/docling/models/easyocr_model.py\", line 7, in <module>\n    import httpx\nModuleNotFoundError: No module named 'httpx'\n```\n...\n\n### Steps to reproduce\n```\npip install --upgrade docling\ndocling test-docling.pdf --to json --to md\n```\n...\n\n### Docling version\n`docling --version` throws the same error message\n...\n\n### Python version\nPython 3.12.1 on Apple M1\n...\n",
    "comments_url": "https://api.github.com/repos/DS4SD/docling/issues/918/comments",
    "author": "HackJack-101",
    "comments": [
      {
        "user": "dolfim-ibm",
        "created_at": "2025-02-07T16:10:12Z",
        "body": "A fixed release will come soon. Meanwhile you can install httpx for not being blocked."
      }
    ]
  },
  {
    "number": 435,
    "title": "Read PDF from local path results in RuntimeError: D:/a/docling-parse/docling-parse/src/v1/proj_folders/pdf_library/core/object/font.h ",
    "created_at": "2024-11-26T07:33:33Z",
    "closed_at": "2024-11-27T11:55:16Z",
    "labels": [
      "bug",
      "pdf parsing"
    ],
    "url": "https://github.com/DS4SD/docling/issues/435",
    "body": "### Bug\r\n<!-- Describe the buggy behavior you have observed. -->\r\nOn Windows 10 x64, I installed docling and try to read a local PDF\r\n\r\n### Steps to reproduce\r\n<!-- Describe the sequence of steps for reproducing the bug. -->\r\ninput_doc_path = Path(r\"C:\\\\Users\\\\\\\\5100670064--0000000000.pdf\")\r\ndoc_converter = DocumentConverter()\r\ndoc_converter.convert(input_doc_path)\r\n\r\nthrows:\r\n\r\nsite-packages\\docling\\backend\\docling_parse_backend.py\", line 195, in __init__\r\n    self.parser = pdf_parser_v1()\r\n                  ^^^^^^^^^^^^^^^\r\nRuntimeError: [D:/a/docling-parse/docling-parse/src/v1/proj_folders/pdf_library/core/object/font.h](file:///D:/a/docling-parse/docling-parse/src/v1/proj_folders/pdf_library/core/object/font.h)\r\n\r\n### Docling version\r\n<!-- Copy the output of `docling --version`. -->\r\nDocling version: 2.7.0\r\nDocling Core version: 2.4.1\r\nDocling IBM Models version: 2.0.6\r\nDocling Parse version: 2.1.2\r\n\r\n### Python version\r\n<!-- Copy the output of `python --version`. -->\r\nPython 3.12.3\r\n\r\n<!-- \u26a0\ufe0f ATTENTION: When sharing screenshots, attachments, or other data make sure not to include any sensitive information. -->\r\n",
    "comments_url": "https://api.github.com/repos/DS4SD/docling/issues/435/comments",
    "author": "bnhemanth",
    "comments": [
      {
        "user": "cau-git",
        "created_at": "2024-11-27T09:32:50Z",
        "body": "@bnhemanth Can you please give us some details:\r\n- Does it happen for just a particular PDF or every PDF?\r\n- Can you check what happens if you use `docling-parse-v2`, example:\r\n```\r\ndocling --pdf-backend dlparse_v2 your_file.pdf\r\n```\r\n\r\nThanks."
      },
      {
        "user": "bnhemanth",
        "created_at": "2024-11-27T09:58:38Z",
        "body": "With docling --pdf-backend dlparse_v2 5100670064--0000000000.pdf\r\nI get: \r\nD:/a/docling-parse/docling-parse/src/resources.h:94     resources-v2-dir does not exist ...\r\nERROR:docling.datamodel.document:An unexpected error occurred while opening the document 5100670064--0000000000.pdf\r\n\\docling-env\\Lib\\site-packages\\docling\\backend\\docling_parse_v2_backend.py\", line 210, in __init__\r\n    self.parser = pdf_parser_v2(\"fatal\")\r\n                  ^^^^^^^^^^^^^^^^^^^^^^\r\nRuntimeError: no existing pdf_resources_dir: C:\\Users\\docling-env\\Lib\\site-packages\\docling_parse\\pdf_resources_v2/\r\nWARNING:docling.cli.main:Document 5100670064--0000000000.pdf failed to convert.\r\n\r\nThis happens for all PDFs. Many Thanks!"
      },
      {
        "user": "PeterStaar-IBM",
        "created_at": "2024-11-27T11:55:16Z",
        "body": "@bnhemanth I suspect that your install is incorrect. The error message suggests that it does not find the resource directory needed. I see also that the errro points to D:/ (D:/a/docling-parse/docling-parse/src/resources.h:94) while your runtime is clearly in C:/ (RuntimeError: no existing pdf_resources_dir: C:\\Users\\docling-env\\Lib\\site-packages\\docling_parse\\pdf_resources_v2/).\r\n\r\nI would propose you do a clean install."
      },
      {
        "user": "bnhemanth",
        "created_at": "2024-11-27T12:45:10Z",
        "body": "Did a re-install with py -m pip install docling \r\nVerified that C:\\Users\\docling-env\\Lib\\site-packages\\docling_parse\\pdf_resources_v2 folder exists. \r\nBut still get the same error. \r\n"
      },
      {
        "user": "zhangwenhao66",
        "created_at": "2024-12-04T03:50:37Z",
        "body": "@bnhemanth I also encountered this problem. The reason I found out was that the path of the running project contained Chinese names. After I changed the project path to an all-English path, there was no error."
      }
    ]
  },
  {
    "number": 113,
    "title": "Missing ONNX file",
    "created_at": "2024-09-27T18:09:29Z",
    "closed_at": "2024-09-30T17:28:10Z",
    "labels": [],
    "url": "https://github.com/DS4SD/docling/issues/113",
    "body": "```\r\n# Initialize the DocumentConverter with the specified options\r\ndoc_converter = DocumentConverter(\r\n    artifacts_path=model_file_path,\r\n    pipeline_options=pipeline_options\r\n)\r\n```\r\n\r\nthat specifically throws the error\r\n```\r\nTraceback (most recent call last):\r\n  File \"<stdin>\", line 1, in <module>\r\n  File \"/home/user/docling/lib/python3.10/site-packages/docling/document_converter.py\", line 54, in __init__\r\n    self.model_pipeline = pipeline_cls(\r\n  File \"/home/user/docling/lib/python3.10/site-packages/docling/pipeline/standard_model_pipeline.py\", line 24, in __init__\r\n    LayoutModel(\r\n  File \"/home/user/docling/lib/python3.10/site-packages/docling/models/layout_model.py\", line 46, in __init__\r\n    self.layout_predictor = LayoutPredictor(\r\n  File \"/home/user/docling/lib/python3.10/site-packages/docling_ibm_models/layoutmodel/layout_predictor.py\", line 98, in __init__\r\n    raise FileNotFoundError(\"Missing ONNX file: {}\".format(self._onnx_fn))\r\nFileNotFoundError: Missing ONNX file: /home/user/.cache/huggingface/hub/models--ds4sd--docling-models/snapshots/ae5a4eedb278abbd529aadd4a9d1091f4ea07291/model_artifacts/layout/beehive_v0.0.5/model.pt/model_artifacts/layout/beehive_v0.0.5/model.pt\r\n```",
    "comments_url": "https://api.github.com/repos/DS4SD/docling/issues/113/comments",
    "author": "thistleknot",
    "comments": [
      {
        "user": "cau-git",
        "created_at": "2024-09-30T07:34:21Z",
        "body": "@thistleknot Could you please report what is in your variable `model_file_path`? You can also remove the `artifacts_path` argument entirely and it should work."
      },
      {
        "user": "kbruegge",
        "created_at": "2025-02-01T20:30:36Z",
        "body": "Hey @cau-git,\n\nI'm having the same issue after a fresh install and executing the example snippet from the README.\n\n```\n<full_path_here>.venv/lib/python3.12/site-packages/docling_ibm_models/layoutmodel/layout_predictor.py\", line 96, in __init__\n    raise FileNotFoundError(\"Missing ONNX file: {}\".format(self._onnx_fn))\nFileNotFoundError: Missing ONNX file: <home_dir>.cache/huggingface/hub/models--ds4sd--docling-models/snapshots/36bebf56681740529abd09f5473a93a69373fbf0/model_artifacts/layout/beehive_v0.0.5/model.pt\n```\n\nI'm on MacOS 15.2 and I'm using `uv` for managing the venv.  Any ideas? Let me know if you need more information."
      }
    ]
  }
]