[
  {
    "number": 4,
    "title": "魔搭社区运行不了",
    "created_at": "2025-01-20T13:39:17Z",
    "closed_at": "2025-01-22T11:30:11Z",
    "labels": [
      "question"
    ],
    "url": "https://github.com/zjunlp/OmniThink/issues/4",
    "body": " 换很多次题目 还是出现ValueError: Expected 2D array, got 1D array instead: array=[]. Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\nTraceback:\nFile \"/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py\", line 85, in exec_func_with_error_handling\n    result = func()\nFile \"/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 576, in code_to_exec\n    exec(code, module.__dict__)\nFile \"/home/studio_service/PROJECT/app.py\", line 151, in <module>\n    article = GenArticle(topic, outline)\nFile \"/home/studio_service/PROJECT/app.py\", line 128, in GenArticle\n    article = ag.generate_article(topic = topic, mindmap = mind_map, article_with_outline = article_with_outline)\nFile \"/home/studio_service/PROJECT/./src/DeepThink/modules/article_generation.py\", line 410, in generate_article\n    section_output_dict_collection.append(future.result())\nFile \"/usr/local/lib/python3.10/concurrent/futures/_base.py\", line 451, in result\n    return self.__get_result()\nFile \"/usr/local/lib/python3.10/concurrent/futures/_base.py\", line 403, in __get_result\n    raise self._exception\nFile \"/usr/local/lib/python3.10/concurrent/futures/thread.py\", line 58, in run\n    result = self.fn(*self.args, **self.kwargs)\nFile \"/home/studio_service/PROJECT/./src/DeepThink/modules/article_generation.py\", line 369, in generate_section\n    collected_info = mindmap.retrieve_information(queries=section_query,\nFile \"/home/studio_service/PROJECT/./src/DeepThink/modules/mindmap.py\", line 651, in retrieve_information\n    sim = cosine_similarity([encoded_query], self.encoded_snippets)[0]\nFile \"/usr/local/lib/python3.10/site-packages/sklearn/utils/_param_validation.py\", line 213, in wrapper\n    return func(*args, **kwargs)\nFile \"/usr/local/lib/python3.10/site-packages/sklearn/metrics/pairwise.py\", line 1679, in cosine_similarity\n    X, Y = check_pairwise_arrays(X, Y)\nFile \"/usr/local/lib/python3.10/site-packages/sklearn/metrics/pairwise.py\", line 194, in check_pairwise_arrays\n    Y = check_array(\nFile \"/usr/local/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 1050, in check_array\n    raise ValueError(msg)",
    "comments_url": "https://api.github.com/repos/zjunlp/OmniThink/issues/4/comments",
    "author": "appleinmusic",
    "comments": [
      {
        "user": "zxlzr",
        "created_at": "2025-01-20T13:53:38Z",
        "body": "抱歉，这个报错是因为api已经达到访问上限，请您等待一段时间再进行访问"
      },
      {
        "user": "zxlzr",
        "created_at": "2025-01-21T04:41:57Z",
        "body": "您好，我们已重启demo并更新关于报错信息（api超上限）的提醒"
      },
      {
        "user": "XeeKee",
        "created_at": "2025-01-21T08:11:36Z",
        "body": "Hello everyone, thank you very much for your interest in omnithink. We have fixed the omnithink demo, and you are welcome to use it again!"
      }
    ]
  }
]